local monitors = require("modules.monitors")
local decorations = require("modules.decorations")
local layouts = require("modules.layouts")
local animations = require("modules.animations")
local misc = require("modules.misc")
local input = require("modules.input")
local keybinds = require("modules.keybinds")
local workspaces = require("modules.workspaces")
local minecraft = require("modules.minecraft")
local windowrules = require("modules.windowrules")

monitors.setup(hl)
decorations.setup(hl)
layouts.setup(hl)
animations.setup(hl)
misc.setup(hl)
input.setup(hl)
keybinds.setup(hl)
workspaces.setup(hl)
minecraft.setup(hl)
windowrules.setup(hl)
